# Generated by Django 5.1.7 on 2025-08-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Title Algorithm"
                    ),
                ),
                ("description", models.TextField(verbose_name="Full Description")),
                (
                    "short_description",
                    models.CharField(max_length=500, verbose_name="Short Description"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="algorithms/image/",
                        verbose_name="Avatar",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "github_link",
                    models.URLField(max_length=500, verbose_name="Github Link"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Algorithm",
                "verbose_name_plural": "Algorithms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Title Projects"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Short Description"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        upload_to="projects/", verbose_name="Main Picture"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "github_link",
                    models.URLField(max_length=500, verbose_name="Github Link"),
                ),
                (
                    "demo_link",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Demo Link"
                    ),
                ),
                (
                    "technologies_used",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Technologies Used"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created_at"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resume/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
            },
        ),
    ]
