# Generated by Django 5.1.7 on 2025-08-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_challenge",
            field=models.TextField(default="", verbose_name="Project Challenge"),
            preserve_default=False,
        ),
    ]
