# Generated by Django 5.1.7 on 2025-08-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_project_project_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="algorithm_challenge",
            field=models.TextField(default="", verbose_name="Algorithm Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="algorithm",
            name="space_complexity",
            field=models.CharField(
                default="", max_length=50, verbose_name="Space Complexity"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="algorithm",
            name="technologies_used",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Technologies Used"
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="time_complexity",
            field=models.CharField(
                default="", max_length=50, verbose_name="Time Complexity"
            ),
            preserve_default=False,
        ),
    ]
