# Generated by Django 5.1.7 on 2025-08-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_algorithm_algorithm_challenge_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algorithm",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Algorithm",
                "verbose_name_plural": "Algorithms",
            },
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="algorithm_challenge",
            field=models.TextField(verbose_name="Algorithm Challenge"),
        ),
    ]
